### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [swaywm/wlroots-rs#166]
```
`` Compiling wlroots-sys v0.0.0 (file:///build/way-cooler-git/src/way-cooler-git/wlroots-rs/wlroots-sys)
   Compiling wlroots v0.0.0 (file:///build/way-cooler-git/src/way-cooler-git/wlroots-rs)
error[E0061]: this function takes 2 parameters but 1 parameter was supplied
   --> src/compositor.rs:218:27
    |
218 |             let backend = wlr_backend_autocreate(display as *mut _);
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error: aborting due to previous error
```

**Comment by psychon** [comment]
Why are you trying to build wlroots-rs against a newer version of wlroots? Apparently the new, second argument to this function was added in commit 24cf70ae9691d605e4a1f7e9d8dc59ec72401bd0 just three days ago while wlroots-rs has its git submodule currently pointing to a wlroots version from eleven days ago.

**Comment by SolarAquarion** [comment]
I'm build wlroots with wlroots-git via a dynamic build.

**Comment by psychon** [comment]
What happens after running `git submodule update --recursive`?

**Comment by SolarAquarion** [comment]
I need to do it again, lol

**Comment by SolarAquarion** [comment]
```
 Compiling wlroots-sys v0.0.0 (file:///home/solaraquarion/build/way-cooler-git/src/way-cooler-git/wlroots-rs/wlroots-sys)
error: failed to run custom build command for `wlroots-sys v0.0.0 (file:///home/solaraquarion/build/way-cooler-git/src/way-cooler-git/wlroots-rs/wlroots-sys)`
process didn't exit successfully: `/home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-61308941f1a3d8f7/build-script-build` (exit code: 101)
--- stdout
src/wlroots.h:48:10: fatal error: 'xcursor.h' file not found, err: true

--- stderr
src/wlroots.h:48:10: fatal error: 'xcursor.h' file not found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: build_script_build::main
             at /checkout/src/libcore/result.rs:782
             at wlroots-rs/wlroots-sys/build.rs:20
  10: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```
i decided to do a commit before the change but i'm getting this build failure

**Comment by Timidger** [comment]
> I'm build wlroots with wlroots-git via a dynamic build.

Don't use that. First it's not supported by the wlroots team, second this library is pinned to an exact commit because wlroots is not stable yet.

If you really want to dynamically link, ensure the correct version is installed.
