### ISSUE TITLE
Build failure at git

### ISSUE THREAD

**Issue by SolarAquarion** [swaywm/wlroots-rs#168]
```
Compiling wlroots-sys v0.0.0 (file:///build/way-cooler-git/src/way-cooler-git/wlroots-rs/wlroots-sys)
error: failed to run custom build command for `wlroots-sys v0.0.0 (file:///build/way-cooler-git/src/way-cooler-git/wlroots-rs/wlroots-sys)`
process didn't exit successfully: `/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-0d6355f6416b5ca2/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=wlroots
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/lib
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/lib64
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/build/
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/util/
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/types/
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/protocol/
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/xcursor/
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/xwayland/
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/backend/
cargo:rustc-link-search=native=/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-48fdef74741a77d4/out/render/
cargo:rustc-link-lib=static=wlr_util
cargo:rustc-link-lib=static=wlr_types
cargo:rustc-link-lib=static=wlr_xcursor
cargo:rustc-link-lib=static=wlr_xwayland
cargo:rustc-link-lib=static=wlr_backend
cargo:rustc-link-lib=static=wlr_render
cargo:rustc-link-lib=static=wl_protos

--- stderr
thread 'main' panicked at 'cannot run command: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
             at /build/rust/src/rustc-1.26.0-src/src/libcore/macros.rs:26
   9: meson::run_command
             at /build/rust/src/rustc-1.26.0-src/src/libcore/result.rs:809
             at /build/.cargo/registry/src/github.com-1ecc6299db9ec823/meson-1.0.0/src/lib.rs:71
  10: meson::build
             at /build/.cargo/registry/src/github.com-1ecc6299db9ec823/meson-1.0.0/src/lib.rs:60
             at /build/.cargo/registry/src/github.com-1ecc6299db9ec823/meson-1.0.0/src/lib.rs:55
  11: build_script_build::main
             at wlroots-rs/wlroots-sys/build.rs:126
             at wlroots-rs/wlroots-sys/build.rs:16
  12: std::rt::lang_start::{{closure}}
             at /build/rust/src/rustc-1.26.0-src/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by Timidger** [comment]
Ensure you have meson installed.
